export const PROJECTS = [
  {
    project_name: 'AKQK 1',
    sub_project_name: '0-27 KM',
    surveyor: 'Mahdi Guliyev',
    report_number: 'H-AK-001',
    status: 'Problemli',
    date: '27.05.2025',
    latitude: 40.02493,
    longitude: 46.91801,
    imageUrl: require('../assets/images/unusedimages/surveyor_images_1.jpg'),
    type: 1,
  },
  {
    project_name: 'AKQK 2',
    sub_project_name: '27-54 KM',
    surveyor: 'Mahdi Guliyev',
    report_number: 'H-AK-002',
    status: 'Problemli',
    date: '27.05.2025',
    latitude: 40.01277,
    longitude: 46.88924,
    imageUrl: require('../assets/images/unusedimages/surveyor_images_2.jpg'),
    type: 1,
  },
  {
    project_name: 'AKQK 3',
    sub_project_name: '54-81 KM',
    surveyor: 'Mahdi Guliyev',
    report_number: 'H-AK-003',
    status: 'Problemli',
    date: '27.05.2025',
    latitude: 39.93441,
    longitude: 46.82899,
    imageUrl: require('../assets/images/unusedimages/surveyor_image_3.jpg'),
    type: 1,
  },
  {
    project_name: 'AKQK 4',
    sub_project_name: 'Yolların bərpası işləri',
    surveyor: 'Yalçın Talıbov',
    report_number: 'H-AK-003',
    status: 'Problemsiz',
    date: '27.05.2025',
    latitude: 40.41533,
    longitude: 46.44439,
    imageUrl: require('../assets/images/unusedimages/surveyor_images_4.jpeg'),
    type: 0,
  },
  {
    project_name: 'AKQK 5',
    sub_project_name: 'Yolların bərpası işləri',
    surveyor: 'Yalçın Talıbov',
    report_number: 'H-AK-003',
    status: 'Problemsiz',
    date: '27.05.2025',
    latitude: 40.77068,
    longitude: 47.04747,
    imageUrl: require('../assets/images/unusedimages/surveyor_images_1.jpg'),
    type: 0,
  },
  {
    project_name: 'AKQK 6',
    sub_project_name: 'Yolların bərpası işləri',
    surveyor: 'Yalçın Talıbov',
    report_number: 'H-AK-003',
    status: 'Problemsiz',
    date: '27.05.2025',
    latitude: 39.35105,
    longitude: 46.58202,
    imageUrl: require('../assets/images/unusedimages/surveyor_images_2.jpg'),
    type: 0,
  },
  {
    project_name: 'AKQK 6461',
    sub_project_name: '0-27 KM',
    surveyor: 'Mahdi Guliyev',
    report_number: 'H-AK-001',
    status: 'Problemli',
    date: '27.05.2025',
    latitude: 39.60136,
    longitude: 47.22499,
    imageUrl: require('../assets/images/unusedimages/surveyor_images_1.jpg'),
    type: 1,
  },
  {
    project_name: 'AKQK 33624',
    sub_project_name: '54-81 KM',
    surveyor: 'Mahdi Guliyev',
    report_number: 'H-AK-003',
    status: 'Problemli',
    date: '27.05.2025',
    latitude: 39.77201,
    longitude: 47.76243,
    imageUrl: require('../assets/images/unusedimages/surveyor_image_3.jpg'),
    type: 1,
  },
  {
    project_name: 'AKQK 453782',
    sub_project_name: 'Yolların bərpası işləri',
    surveyor: 'Yalçın Talıbov',
    report_number: 'H-AK-003',
    status: 'Problemsiz',
    date: '27.05.2025',
    latitude: 39.91895,
    longitude: 48.43887,
    imageUrl: require('../assets/images/unusedimages/surveyor_images_4.jpeg'),
    type: 0,
  },
  {
    project_name: 'AKQK 225234',
    sub_project_name: '27-54 KM',
    surveyor: 'Mahdi Guliyev',
    report_number: 'H-AK-002',
    status: 'Problemli',
    date: '27.05.2025',
    latitude: 40.42758,
    longitude: 49.88523,
    imageUrl: require('../assets/images/unusedimages/surveyor_images_2.jpg'),
    type: 1,
  },
];
