import {Dimensions, Platform, StyleSheet} from 'react-native';
import {FONTS} from '@components/styles/fonts';

const {width} = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  map_header: {
    position: 'absolute',
    left: 20,
    zIndex: 10,
  },
  map_header_back: {
    backgroundColor: '#FFF',
    padding: 14,
    borderRadius: 30,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 5,
    marginTop: Platform.OS === 'android' ? 20 : 10,
  },
  map_main: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    bottom: 0,
  },
  map_controls: {
    position: 'absolute',
    right: 20,
    flexDirection: 'column',
    gap: 10,
  },
  map_controls_button: {
    backgroundColor: '#FFF',
    padding: 14,
    borderRadius: 30,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 5,
  },

  map_filter_group: {
    flexDirection: 'column',
    position: 'absolute',
    top: -100,
    width: '100%',
    paddingHorizontal: 20,
  },
  map_filter_group_button: {
    display: 'flex',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'flex-start',
  },
  map_filter_group_button_2: {
    display: 'flex',
    flexDirection: 'row',
    top: 10,
    gap: 10,
    justifyContent: 'flex-start',
  },
  map_filter_group_button_item: {
    flexDirection: 'row',
    backgroundColor: '#FFF',
    paddingLeft: 5,
    paddingRight: 20,
    borderRadius: 10,
    paddingVertical: 5,
    gap: 10,
    alignItems: 'center',
  },
  map_filter_group_button_item_icon: {
    padding: 7,
    borderRadius: 10,
    backgroundColor: '#F3F7FB',
  },
  map_filter_group_button_item_text: {
    fontSize: 14,
    fontFamily: FONTS.sfProRoundedFontFamily,
    color: '#000',
    fontWeight: '500',
  },
  map_laction: {
    position: 'absolute',
    right: -20,
    top: -10,
    marginLeft: 'auto',
  },
  map_location_button: {
    backgroundColor: '#FFF',
    padding: 14,
    borderRadius: 30,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 5,
  },
  // map item styles
  map_searchbar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderRadius: 20,
    paddingHorizontal: 30,
    height: 60,
    marginBottom: 30,
  },
  map_search_input: {
    backgroundColor: 'transparent',
    width: '90%',
    height: '100%',
    fontFamily: FONTS.sfProRoundedFontFamily,
    fontSize: 16,
    fontWeight: '500',
    color: '#000',
  },
  map_search_input_active: {
    borderColor: '#0B5AAE',
  },
  flatLisPadding: {
    paddingBottom: 420,
  },
  map_item_card: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 10,
    marginBottom: 15,
  },
  map_item_card_icon: {
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f9f3fb',
    borderRadius: 10,
  },
  map_item_card_text_container: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-start',
    gap: 5,
  },
  map_item_card_text_title: {
    fontFamily: FONTS.sfProRoundedFontFamily,
    fontSize: 14,
    color: '#000',
    fontWeight: '500',
  },
  map_item_card_text_content: {
    fontFamily: FONTS.sfProRoundedFontFamily,
    fontSize: 12,
    color: '#8B8B8B',
    fontWeight: '400',
  },
  map_detail_header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 30,
  },
  map_detail_header_icon: {
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F3F7FB',
    borderRadius: 10,
  },
  map_detail_header_text_container: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-start',
    gap: 5,
  },
  map_detail_header_text_title: {
    fontFamily: FONTS.sfProRoundedFontFamily,
    fontSize: 14,
    color: '#000',
    fontWeight: '500',
  },
  map_detail_header_text_content: {
    fontFamily: FONTS.sfProRoundedFontFamily,
    fontSize: 12,
    color: '#8B8B8B',
    fontWeight: '400',
  },
  map_detail_button: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderRadius: 20,
    marginTop: 10,
    overflow: 'hidden',
    marginBottom: 30,
  },
  map_detail_button_container: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
  },
  map_detail_button_text: {
    fontFamily: FONTS.sfProRoundedFontFamily,
    fontSize: 16,
    color: '#fff',
    fontWeight: '500',
  },
  map_detail_card: {
    flexDirection: 'column',
    justifyContent: 'flex-start',
    padding: 20,
    borderRadius: 20,
    marginBottom: 20,
    overflow: 'hidden',
    borderColor: '#D7D7D7',
    borderWidth: 1,
  },
  map_detail_card_label: {
    fontFamily: FONTS.sfProRoundedFontFamily,
    fontSize: 13,
    color: '#8B8B8B',
    fontWeight: '400',
  },
  map_detail_card_text: {
    fontFamily: FONTS.sfProRoundedFontFamily,
    fontSize: 14,
    color: '#000',
    fontWeight: '500',
    marginTop: 5,
  },
  mt20: {
    marginTop: 20,
  },
  image_container: {
    width: '100%',
    aspectRatio: 1.9,
    overflow: 'hidden',
    marginBottom: 20,
  },
  image: {
    width: '100%',
    height: '100%',
    borderRadius: 20,
  },
});
